# Вариант 1

In [8]:
import pandas as pd
import numpy as np

# Практическая работа 2
### Исходные данные

In [9]:
sales = pd.DataFrame({
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone', 'Laptop', 'Tablet', 'Phone', 'Laptop', 'Tablet'],
    'Quantity': [1, 2, 1, 3, 1, 2, 1, 4, 1, 2],
    'Price': [50000, 30000, 20000, 50000, np.nan, 50000, 20000, 30000, 50000, np.nan],
    'Region': ['Moscow', 'SPb', 'Kazan', 'Moscow', 'SPb', 'Kazan', np.nan, 'SPb', 'Moscow', 'Kazan']
})
products = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet', 'Monitor'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Accessories'],
    'Weight_kg': [2.5, 0.2, 0.5, 3.0]
})
display(sales)
display(products)

   OrderID Product  Quantity    Price  Region
0      101  Laptop         1  50000.0  Moscow
1      102   Phone         2  30000.0     SPb
2      103  Tablet         1  20000.0   Kazan
3      104  Laptop         3  50000.0  Moscow
4      105   Phone         1      NaN     SPb
5      106  Laptop         2  50000.0   Kazan
6      107  Tablet         1  20000.0     NaN
7      108   Phone         4  30000.0     SPb
8      109  Laptop         1  50000.0  Moscow
9      110  Tablet         2      NaN   Kazan

   Product     Category  Weight_kg
0   Laptop  Electronics        2.5
1    Phone  Electronics        0.2
2   Tablet  Electronics        0.5
3  Monitor  Accessories        3.0

### Задание 1. Найти общее количество продаж (сумму Quantity) для каждого продукта

In [10]:
sales.groupby('Product')['Quantity'].sum()

Product
Laptop    7
Phone     7
Tablet    4
Name: Quantity, dtype: int64

### Задание 2. Найти среднюю цену для каждого региона

In [11]:
sales.groupby('Region')['Price'].mean()

Region
Kazan     35000.0
Moscow    50000.0
SPb       30000.0
Name: Price, dtype: float64

### Задание 3. Заполнить пропуски в столбце Price средним значением

In [12]:
sales['Price'] = sales['Price'].fillna(sales['Price'].mean())
sales

   OrderID Product  Quantity    Price  Region
0      101  Laptop         1  50000.0  Moscow
1      102   Phone         2  30000.0     SPb
2      103  Tablet         1  20000.0   Kazan
3      104  Laptop         3  50000.0  Moscow
4      105   Phone         1  37500.0     SPb
5      106  Laptop         2  50000.0   Kazan
6      107  Tablet         1  20000.0     NaN
7      108   Phone         4  30000.0     SPb
8      109  Laptop         1  50000.0  Moscow
9      110  Tablet         2  37500.0   Kazan

### Задание 4. Отсортировать таблицу sales по столбцу Quantity по убыванию

In [13]:
sales.sort_values('Quantity', ascending=False)

   OrderID Product  Quantity    Price  Region
7      108   Phone         4  30000.0     SPb
3      104  Laptop         3  50000.0  Moscow
1      102   Phone         2  30000.0     SPb
5      106  Laptop         2  50000.0   Kazan
9      110  Tablet         2  37500.0   Kazan
0      101  Laptop         1  50000.0  Moscow
2      103  Tablet         1  20000.0   Kazan
4      105   Phone         1  37500.0     SPb
6      107  Tablet         1  20000.0     NaN
8      109  Laptop         1  50000.0  Moscow

### Задание 5. Объединить таблицы sales и products по столбцу Product (inner join)

In [14]:
pd.merge(sales, products, on='Product', how='inner')

   OrderID Product  Quantity    Price  Region     Category  Weight_kg
0      101  Laptop         1  50000.0  Moscow  Electronics        2.5
1      102   Phone         2  30000.0     SPb  Electronics        0.2
2      103  Tablet         1  20000.0   Kazan  Electronics        0.5
3      104  Laptop         3  50000.0  Moscow  Electronics        2.5
4      105   Phone         1  37500.0     SPb  Electronics        0.2
5      106  Laptop         2  50000.0   Kazan  Electronics        2.5
6      107  Tablet         1  20000.0     NaN  Electronics        0.5
7      108   Phone         4  30000.0     SPb  Electronics        0.2
8      109  Laptop         1  50000.0  Moscow  Electronics        2.5
9      110  Tablet         2  37500.0   Kazan  Electronics        0.5